webtalk_init -webtalk_dir E:/terme 7/FPGA/Prj1/9633022_Prj/project_2/project_2.sim/sim_1/behav/xsim/xsim.dir/edgefilt_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Feb  8 10:32:21 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2552052" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "a9a51f49-3313-4892-a4e3-134f36c230ac" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "e80c2d4d77ef479b90902bf9d3ee9d8d" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "15" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2712 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "193600500 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "3" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "2.05_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "14260_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3853306351 -regid "" -xml E:/terme 7/FPGA/Prj1/9633022_Prj/project_2/project_2.sim/sim_1/behav/xsim/xsim.dir/edgefilt_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html E:/terme 7/FPGA/Prj1/9633022_Prj/project_2/project_2.sim/sim_1/behav/xsim/xsim.dir/edgefilt_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm E:/terme 7/FPGA/Prj1/9633022_Prj/project_2/project_2.sim/sim_1/behav/xsim/xsim.dir/edgefilt_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
